build:
  maxIssues: 1
  excludeCorrectable: true
  weights:
    # Uncomment and adjust weights for specific rules as needed
    exceptions: 3
    complexity: 2
    LongParameterList: 1
    style: 1
    comments: 1

config:
  validation: true
  warningsAsErrors: true
  checkExhaustiveness: false
  # when writing own rules with new properties, exclude the property path e.g.: 'my_rule_set,.*>.*>[my_property]'
  excludes: ''

console-reports:
  active: true
  exclude:
    - 'ProjectStatisticsReport'
    - 'ComplexityReport'
    - 'NotificationReport'
    - 'FindingsReport'
    - 'FileBasedFindingsReport'
    #- 'LiteFindingsReport'

# Jetpack Compose specific naming rules
naming:
  FunctionNaming:
    active: true
    ignoreAnnotated: [ 'Composable' ]  # Allow PascalCase for @Composable functions
    functionPattern: '[a-z][a-zA-Z0-9]*'
  TopLevelPropertyNaming:
    active: true
    constantPattern: '[A-Z][A-Za-z0-9]*'  # Allow PascalCase for Compose constants like FooPadding

style:
  MaxLineLength:
    active: true
    maxLineLength: 150
    excludePackageStatements: true
    excludeImportStatements: true
    excludeCommentStatements: false
    excludeRawStrings: true
  MagicNumber:
    active: true
    ignoreNumbers: [ '-1', '0', '1', '2' ]
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: true  # Allow magic numbers in Color(0xFF...) declarations
    ignoreLocalVariableDeclaration: false
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotation: false
    ignoreNamedArgument: true
    ignoreEnums: false
    ignoreRanges: false
    ignoreExtensionFunctions: true
  UnusedPrivateMember:
    active: true
    ignoreAnnotated: [ 'Preview' ]  # Allow unused @Preview functions
  WildcardImport:
    active: true
    excludes: [ '**/test/**', '**/androidTest/**' ] # Exclude test files from wildcard import checks

complexity:
  active: true
  CognitiveComplexMethod:
    active: false
    threshold: 15
  ComplexInterface:
    active: false
    threshold: 10
    includeStaticDeclarations: false
    includePrivateDeclarations: false
    ignoreOverloaded: false
  LargeClass:
    active: true
    threshold: 600
  LongMethod:
    active: false  # Disabled for Compose as composables can be longer
    threshold: 60
  LongParameterList:
    active: true
    functionThreshold: 15  # Increased for Compose functions with many parameters
    constructorThreshold: 7
    ignoreDefaultParameters: true  # Ignore parameters with default values
    ignoreDataClasses: true
    ignoreAnnotatedParameter: [ 'Composable' ]
  TooManyFunctions:
    active: true
    excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/androidUnitTest/**', '**/androidInstrumentedTest/**', '**/jsTest/**', '**/iosTest/**' ]
    thresholdInFiles: 15  # Increased for files with many @Preview functions
    thresholdInClasses: 15
    thresholdInInterfaces: 11
    thresholdInObjects: 11
    thresholdInEnums: 11
    ignoreDeprecated: false
    ignorePrivate: false
    ignoreOverridden: false
    ignoreAnnotatedFunctions: [ 'Preview' ]  # Ignore @Preview functions
    ignoreAnnotated: [ 'dagger.Module' ] # Ignore classes annotated with @Module

exceptions:
  active: true
  TooGenericExceptionCaught:
    active: true
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/androidUnitTest/**', '**/androidInstrumentedTest/**', '**/jsTest/**', '**/iosTest/**']
    exceptionNames:
      - 'Error'
      - 'Exception'
      - 'NullPointerException'
      - 'RuntimeException'
      - 'Throwable'
    allowedExceptionNameRegex: '_|(ignore|expected).*'
  TooGenericExceptionThrown:
    active: true
    exceptionNames:
      - 'Error'
      - 'Exception'
      - 'RuntimeException'
      - 'Throwable'
